### ISSUE TITLE
guacadmin / guacadmin doesn't allow access to guacamole

### ISSUE THREAD

**Issue by StewAlexanderACC** [oznu/docker-guacamole#38]
@oznu 
log messages:
```
Starting guacamole client...
25-Jul-2019 14:33:22.700 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.14
25-Jul-2019 14:33:22.702 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 6 2018 21:13:53 UTC
25-Jul-2019 14:33:22.702 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.14.0
25-Jul-2019 14:33:22.703 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
25-Jul-2019 14:33:22.703 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-55-generic
25-Jul-2019 14:33:22.703 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
25-Jul-2019 14:33:22.703 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
25-Jul-2019 14:33:22.703 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_181-8u181-b13-2~deb9u1-b13
25-Jul-2019 14:33:22.703 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
25-Jul-2019 14:33:22.704 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
25-Jul-2019 14:33:22.705 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
25-Jul-2019 14:33:22.705 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
25-Jul-2019 14:33:22.706 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
25-Jul-2019 14:33:22.706 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
25-Jul-2019 14:33:22.706 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
25-Jul-2019 14:33:22.706 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
25-Jul-2019 14:33:22.706 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
25-Jul-2019 14:33:22.706 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
25-Jul-2019 14:33:22.707 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
25-Jul-2019 14:33:22.707 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
25-Jul-2019 14:33:22.707 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.19] using APR version [1.5.2].
25-Jul-2019 14:33:22.707 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
25-Jul-2019 14:33:22.707 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
25-Jul-2019 14:33:22.714 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0j  20 Nov 2018]
25-Jul-2019 14:33:22.819 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
25-Jul-2019 14:33:22.850 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
25-Jul-2019 14:33:22.853 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [637] milliseconds
25-Jul-2019 14:33:22.885 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
25-Jul-2019 14:33:22.885 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.14]
25-Jul-2019 14:33:22.910 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
25-Jul-2019 14:33:24.321 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
14:33:24.712 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
14:33:24.808 [main] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
14:33:25.053 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
14:33:25.208 [main] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
25-Jul-2019 14:33:25.611 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.RESTExceptionMapper as a provider class
25-Jul-2019 14:33:25.611 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.extension.ExtensionRESTService as a root resource class
25-Jul-2019 14:33:25.612 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.language.LanguageRESTService as a root resource class
25-Jul-2019 14:33:25.612 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.patch.PatchRESTService as a root resource class
25-Jul-2019 14:33:25.612 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.auth.TokenRESTService as a root resource class
25-Jul-2019 14:33:25.612 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.session.SessionRESTService as a root resource class
25-Jul-2019 14:33:25.612 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.codehaus.jackson.jaxrs.JacksonJsonProvider as a provider class
25-Jul-2019 14:33:25.616 INFO [main] com.sun.jersey.server.impl.application.WebApplicationImpl._initiate Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
25-Jul-2019 14:33:25.717 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.RESTExceptionMapper to GuiceManagedComponentProvider with the scope "Singleton"
25-Jul-2019 14:33:25.720 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.codehaus.jackson.jaxrs.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
25-Jul-2019 14:33:26.356 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.extension.ExtensionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
25-Jul-2019 14:33:26.363 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.language.LanguageRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
25-Jul-2019 14:33:26.364 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.patch.PatchRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
25-Jul-2019 14:33:26.369 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.auth.TokenRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
25-Jul-2019 14:33:26.370 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.session.SessionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
25-Jul-2019 14:33:26.394 INFO [main] org.webjars.servlet.WebjarsServlet.init WebjarsServlet initialization completed
25-Jul-2019 14:33:26.416 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [3,506] ms
25-Jul-2019 14:33:26.417 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
25-Jul-2019 14:33:26.449 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [32] ms
25-Jul-2019 14:33:26.449 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
25-Jul-2019 14:33:26.465 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [16] ms
25-Jul-2019 14:33:26.465 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
25-Jul-2019 14:33:26.697 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [232] ms
25-Jul-2019 14:33:26.700 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
25-Jul-2019 14:33:26.733 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [33] ms
25-Jul-2019 14:33:26.738 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
25-Jul-2019 14:33:26.802 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
25-Jul-2019 14:33:26.836 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [3,982] milliseconds
25-Jul-2019 14:33:48.508 INFO [http-nio-8080-exec-3] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:414)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

25-Jul-2019 14:33:48.508 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:414)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

25-Jul-2019 14:33:48.549 INFO [http-nio-8080-exec-4] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:414)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

14:36:43.564 [http-nio-8080-exec-10] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.16.1.193 for user "guacadmin" failed.
14:36:56.312 [http-nio-8080-exec-7] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.16.1.193 for user "guacadmin" failed.
14:37:15.897 [http-nio-8080-exec-6] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.16.1.193 for user "guacadmin" failed.
14:37:18.872 [http-nio-8080-exec-8] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.16.1.193 for user "guacadmin" failed.
14:37:27.608 [http-nio-8080-exec-5] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.16.1.193 for user "admin" failed.
14:37:47.643 [http-nio-8080-exec-9] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.16.1.193 for user "guacadmin" failed.
14:39:41.074 [http-nio-8080-exec-2] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.16.1.193 for user "" failed.
14:39:51.984 [http-nio-8080-exec-3] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.16.1.193 for user "guacadmin" failed.
```

**Comment by StewAlexanderACC** [comment]
Looks like the guacamole password is "null" from the looks of this file:
```                                                                                                                                              
root@d547ca403228:/config/guacamole# cat guacamole.properties                                                                                                                                                        
postgresql-hostname: localhost                                                                                                                                                                                       
postgresql-port: 5432                                                                                                                                                                                                
postgresql-database: guacamole_db                                                                                                                                                                                    
postgresql-username: guacamole                                                                                                                                                                                       
postgresql-password: null                                                                                                                                                                                            
                                                                                                                                                                                                                     
# ldap-hostname: ldap.example.net                                                                                                                                                                                    
# ldap-port: 389                                                                                                                                                                                                     
# ldap-encryption-method: none                                                                                                                                                                                       
# ldap-max-search-results: 1000                                                                                                                                                                                      
# ldap-search-bind-dn:                                                                                                                                                                                               
# ldap-search-bind-password:                                                                                                                                                                                         
# ldap-user-base-dn: ou=people,dc=example,dc=net                                                                                                                                                                     
# ldap-username-attribute: uid                                                                                                                                                                                       
# ldap-user-search-filter: (objectClass=*) 
```

**Comment by StewAlexanderACC** [comment]
@oznu 
Typing nothing for the password doesn't work, typing null as a password doesn't work, typing guacadmin doesn't work, ideas?

**Comment by StewAlexanderACC** [comment]
Saw some notes. restarted the container worked

**Comment by blancmatter** [comment]
I'm having the same issue.

Have started the container with 

```shell
 docker run -p 8080:8080 -v /config oznu/guacamole
```

using guacadmin and guacadmin as default un and pw gives the following error;

```shell
11:54:01.633 [http-nio-8080-exec-4] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.17.0.1 for user "guacadmin" failed.
```

**Comment by StewAlexanderACC** [comment]
@blancmatter Restarting the container worked for me (I restarted it using Cockpit, as in: `$sudo apt-get install  Cockpit. Cockpit-Docker, Cockpit-ws and Cockpit-packagekit`, https://cockpit-project.org)

> I'm having the same issue.
> 
> Have started the container with
> 
> ```shell
>  docker run -p 8080:8080 -v /config oznu/guacamole
> ```
> 
> using guacadmin and guacadmin as default un and pw gives the following error;
> 
> ```shell
> 11:54:01.633 [http-nio-8080-exec-4] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 172.17.0.1 for user "guacadmin" failed.
> ```

**Comment by blancmatter** [comment]
Thanks @StewAlexanderACC 

I just did the following and it all worked,

```shell
docker restart <containername>
```

Thanks, still having issues getting any VNC stuff working though!

**Comment by m1dm1a** [comment]
Same as above, restarting the container after initial "docker run" creation allows login tho the guacadmin user.

**Comment by StewAlexanderACC** [comment]
@blancmatter / @m1dm1a - no one else is taking a look at this, so closing it.

What the heck the development team on this is doing is anyone's guess
